### ISSUE TITLE
requests.exceptions.HTTPError: 400 https://api.spotify.com/v1/recommendations?limit=50&market=from_token

### ISSUE THREAD

**Issue by pvincent4** [akago-dev/o2m#12]
python3 main.py 
NFCReader initializing...
Insert or remove a smartcard in the system.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/o2m/o2m/lib/spotipy/client.py", line 164, in _internal_call
    r.raise_for_status()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/recommendations?limit=50&market=from_token

**Comment by akago-dev** [comment]
try catch sur l'erreur HTTPError avec print dans le catch
