### ISSUE TITLE
[iris:playlist] Bug lecture chaines podcasts dans playlist:iris

### ISSUE THREAD

**Issue by pvincent4** [akago-dev/o2m#26]
Tag : TAG UID : 04CFB9193E2580 | TYPE : iris:playlist | MEDIA : m3u:Podcast2listen.m3u8 | DESCRIPTION : Carte - Piano | READ COUNT : 17
podcast+http://radiofrance-podcast.net/podcast09/rss_13904.xml
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.7/site-packages/smartcard/CardMonitoring.py", line 180, in run
    (addedcards, removedcards))
  File "/home/pi/.local/lib/python3.7/site-packages/smartcard/Observer.py", line 62, in notifyObservers
    observer.update(self, arg)
  File "/home/pi/o2m/src/nfcreader.py", line 63, in update
    self.events.on_change(addedcards, removedcards, self.active_cards) # Launch the event
  File "/home/pi/.local/lib/python3.7/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/pi/o2m/src/nfcreader.py", line 172, in update_change
    self.o2m.get_new_cards(addedCards, removedCards, activeCards)
  File "main.py", line 80, in get_new_cards
    self.one_tag_changed(tag)
  File "main.py", line 199, in one_tag_changed
    shows = self.get_podcast_from_url(feedurl)
  File "main.py", line 224, in get_podcast_from_url
    f = Extension.get_url_opener(self.config).open(url, timeout=10)
  File "/usr/lib/python3/dist-packages/mopidy_podcast/__init__.py", line 48, in get_url_opener
    proxy = httpclient.format_proxy(config["proxy"])
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'proxy'

^Cpi@pi:~/o2m $ cd /home/pi/o2m/ && python3 main.py 
NFCReader initializing...
Insert or remove a smartcard in the system.

Tag : TAG UID : 045340D2204B80 | TYPE : radio | MEDIA : tunein:station:s24875 | DESCRIPTION : France Inter | READ COUNT : 238
Adding 1 tracks
stopped
no current track : Playing first track
Active tags count: 1

**Comment by pvincent4** [comment]
m3u
[Podcast2listen.zip](https://github.com/akago-dev/o2m/files/4471628/Podcast2listen.zip)

**Comment by pvincent4** [comment]
@akago-dev patch temporaire dans dernier commit 
main.py:238
`        f = Extension.get_url_opener({"proxy":{}}).open(url, timeout=10)`
